apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa

  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: jocajunior77/go-hpa:latest
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m

---

apiVersion: v1
kind: Service
metadata:
  name: go-hpa
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8001
  selector:
    app: go-hpa


---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-autoscaler
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15

